name: qsar-flash
channels:
  - pytorch
  - pyg
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - pyg=2.0.4
  - python=3.9.*
  - pip=21.2.4
  - dgl-cuda11.3=0.8.0post1
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - lightning-flash=0.7.1
  - rdkit=2021.09.5
  - sympy=1.10.1
  - wandb=0.12.11
  - pre-commit=2.17.0
  - ase=3.22.1
  - pip:
    - class-resolver==0.3.8
platforms:
  - linux-64
